/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        surface: "#faf8ff",
        "secondary-fixed": "#ffdad6",
        "on-tertiary-fixed": "#002113",
        "on-surface-variant": "#5c403c",
        "inverse-primary": "#ffb4ab",
        "on-surface": "#131b2e",
        "on-secondary-container": "#690007",
        "surface-container-high": "#e2e7ff",
        "tertiary-fixed": "#6ffbbe",
        "surface-container": "#eaedff",
        "primary-fixed-dim": "#ffb4ab",
        error: "#ba1a1a",
        "primary-fixed": "#ffdad6",
        "on-background": "#131b2e",
        "on-tertiary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-highest": "#dae2fd",
        "surface-container-low": "#f2f3ff",
        "surface-tint": "#bf0715",
        primary: "#b70011",
        "on-secondary-fixed-variant": "#8e1214",
        "on-primary-fixed-variant": "#93000b",
        "on-primary-fixed": "#410002",
        "primary-container": "#dc2626",
        background: "#faf8ff",
        "on-primary-container": "#fff6f5",
        "surface-bright": "#faf8ff",
        "surface-variant": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#410002",
        "on-tertiary-container": "#e1ffec",
        "on-secondary": "#ffffff",
        "inverse-surface": "#283044",
        "tertiary-fixed-dim": "#4edea3",
        outline: "#916f6b",
        tertiary: "#006645",
        "secondary-container": "#ff665c",
        "inverse-on-surface": "#eef0ff",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#ffb4ac",
        "surface-container-lowest": "#ffffff",
        "outline-variant": "#e6bdb8",
        "error-container": "#ffdad6",
        secondary: "#b02d29",
        "on-tertiary-fixed-variant": "#005236",
        "tertiary-container": "#008259",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-md": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "gutter-mobile": "1rem",
        "space-sm": "0.5rem",
        margin: "2rem",
        gutter: "1.5rem",
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
